

import streamlit as st
from openai import OpenAI
import os

st.title("🤖 OpenAI Helper")

# 1. Load Key
try:
    api_key = st.secrets["OPENAI_API_KEY"]
except (FileNotFoundError, KeyError):
    api_key = os.getenv("OPENAI_API_KEY")

if not api_key:
    st.error("❌ OPENAI_API_KEY not found.")
    st.stop()

client = OpenAI(api_key=api_key)

# 2. App Logic
user_input = st.text_input("What do you want to know?")

if st.button("Ask AI"):
    if not user_input:
        st.warning("Please type something first.")
    else:
        try:
            with st.spinner("Thinking..."):
                # We request "gpt-4o-mini"
                response = client.chat.completions.create(
                    model="gpt-4o-mini", 
                    messages=[{"role": "user", "content": user_input}]
                )
                
                # --- THIS IS THE NEW PART ---
                
                # 1. Print the answer
                st.write(response.choices[0].message.content)
                
                # 2. Print the exact version used
                # response.model gives the specific version (e.g., gpt-4o-mini-2024-07-18)
                st.success(f"📌 Answer generated by version: **{response.model}**")
                
        except Exception as e:
            st.error(f"Error: {e}")
